### ISSUE TITLE
Uploaded images are not shown in the preview of markdown

### ISSUE THREAD

**Issue by BBasile** [tiensonqin/lambdahackers#8]
But using `![]()` works

**Comment by tiensonqin** [comment]
Thanks for trying lambdahackers!

Could you paste your text here?
Also is the format markdown or asciidoc?

**Comment by BBasile** [comment]
i used markdown and after uploading i got something like `image::<some_address>`. But once published the image don't show at all. Maybe this is because you deactivated mardown or something ([blog post](https://lambdahackers.com/@b4asile/why-d-is-a-good-choice-for-writing-a-toy-language-4vapyvas5a))

**Comment by tiensonqin** [comment]
Oh, I got it, yeah, it's a bug! 
I'll fix this soon.

**Comment by tiensonqin** [comment]
@BBasile I changed your post's format to markdown, now you can see the result.

**Comment by BBasile** [comment]
After fixing a few typos the formatting is lost again.
I suppose that the bug is not fixed and that you manually changed something ?
I'll wait before sharing the link anyway.

**Comment by tiensonqin** [comment]
@BBasile Yeah, I see your format back to `asciidoc`, maybe there's a bug on switching format.

**Comment by BBasile** [comment]
Yeah this is a bug, I have to switch to asciidoc and then back to markdown to get the right formatting again.

**Comment by tiensonqin** [comment]
Fixed now! 
Comment if it does not work for you.
